version: 2.1
commands:
  accept-licenses:
    description: |
      Accept all Android SDK Manager licenses
    steps:
    - run:
        command: |
          yes | sdkmanager --licenses
          yes | sdkmanager --update
        description: |
          Accepts all Android SDK licenses. This command is typically not necessary to execute, since the CircleCI convenience images ship with all licenses accepted. This command will add approximately 10 seconds to the build time.
        name: Accept Android Licenses
        shell: /bin/bash -e

jobs:
  build:
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - accept-licenses
      - run: "pwd"
      - run: "ls -l"
      - run: "chmod +x build.sh"
      - run: ./build.sh
      - store_artifacts:
         path: artifacts/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: conviva_deploy
          filters: 
            tags:
              only: /.*/
            branches:
              ignore: /.*/
